/**
 * Sprint Status File Generator
 *
 * Generates sprint-status.yaml file to track all epics and stories with metadata
 * for workflow management. The sprint status file serves as the single source of
 * truth for tracking development progress throughout the sprint.
 *
 * @module solutioning/sprint-status-generator
 * @see docs/stories/4-7-sprint-status-file-generation.md
 */

import { Story } from './types.js';
import { SolutioningResult } from './solutioning-orchestrator.js';

/**
 * Sprint Status Generator
 *
 * Generates YAML-formatted sprint status file from SolutioningResult.
 * Includes project metadata, status definitions, and hierarchical epic/story tracking.
 *
 * @example
 * ```typescript
 * const generator = new SprintStatusGenerator();
 * const yaml = generator.generateSprintStatus(result, 'Agent Orchestrator');
 * await fs.writeFile('docs/sprint-status.yaml', yaml, 'utf-8');
 * ```
 */
export class SprintStatusGenerator {
  /**
   * Generate sprint status YAML from SolutioningResult
   *
   * Creates a complete sprint-status.yaml file with:
   * - Project metadata (date, name, key, tracking system, story location)
   * - Status definitions header (epic, story, retrospective statuses)
   * - Workflow notes for SM guidance
   * - Development status tracking (epic → stories → retrospective)
   *
   * @param result SolutioningResult with epics and stories
   * @param projectName Name of the project (e.g., "Agent Orchestrator")
   * @returns YAML string ready to be written to file
   *
   * @example
   * ```typescript
   * const generator = new SprintStatusGenerator();
   * const result = await orchestrator.executeSolutioning('docs/PRD.md', 'docs/architecture.md');
   * const yaml = generator.generateSprintStatus(result, 'My Project');
   * ```
   */
  generateSprintStatus(result: SolutioningResult, projectName: string): string {
    const yaml: string[] = [];

    // YAML header with comments
    yaml.push('# Sprint Status Tracking');
    yaml.push('# Generated by sprint-planning workflow');
    yaml.push(`# Date: ${this.getCurrentDate()}`);
    yaml.push('');

    // Project metadata
    yaml.push(`generated: ${this.getCurrentDate()}`);
    yaml.push(`project: ${projectName}`);
    yaml.push(`project_key: ${this.generateProjectKey(projectName)}`);
    yaml.push(`tracking_system: file-system`);
    yaml.push(`story_location: "{project-root}/docs/stories"`);
    yaml.push('');

    // Status definitions header
    yaml.push('# STATUS DEFINITIONS:');
    yaml.push('# ==================');
    yaml.push('# Epic Status:');
    yaml.push('#   - backlog: Epic exists in epic file but not contexted');
    yaml.push('#   - contexted: Epic tech context created (required before drafting stories)');
    yaml.push('#');
    yaml.push('# Story Status:');
    yaml.push('#   - backlog: Story only exists in epic file');
    yaml.push('#   - drafted: Story file created in stories folder');
    yaml.push('#   - ready-for-dev: Draft approved and story context created');
    yaml.push('#   - in-progress: Developer actively working on implementation');
    yaml.push('#   - review: Under SM review (via code-review workflow)');
    yaml.push('#   - done: Story completed');
    yaml.push('#');
    yaml.push('# Retrospective Status:');
    yaml.push('#   - optional: Can be completed but not required');
    yaml.push('#   - completed: Retrospective has been done');
    yaml.push('#');
    yaml.push('# WORKFLOW NOTES:');
    yaml.push('# ===============');
    yaml.push('# - Epics should be \'contexted\' before stories can be \'drafted\'');
    yaml.push('# - Stories can be worked in parallel if team capacity allows');
    yaml.push('# - SM typically drafts next story after previous one is \'done\' to incorporate learnings');
    yaml.push('# - Dev moves story to \'review\', SM reviews, then Dev moves to \'done\'');
    yaml.push('');

    // Development status section
    yaml.push('development_status:');

    // Add each epic with its stories and retrospective
    for (const epic of result.epics) {
      yaml.push(`  # ${epic.title}`);
      yaml.push(`  ${epic.id}: backlog`);

      // Add stories for this epic
      for (const story of epic.stories) {
        const storyKey = this.formatStoryKey(story);
        yaml.push(`  ${storyKey}: backlog`);
      }

      // Add retrospective
      yaml.push(`  ${epic.id}-retrospective: optional`);
      yaml.push('');
    }

    return yaml.join('\n');
  }

  /**
   * Get current date in YYYY-MM-DD format
   *
   * @returns Current date string
   */
  private getCurrentDate(): string {
    const now = new Date();
    const year = now.getFullYear();
    const month = String(now.getMonth() + 1).padStart(2, '0');
    const day = String(now.getDate()).padStart(2, '0');
    return `${year}-${month}-${day}`;
  }

  /**
   * Generate project key from project name
   *
   * Converts project name to kebab-case key
   * Example: "Agent Orchestrator" → "agent-orchestrator"
   *
   * @param projectName Project name
   * @returns Project key in kebab-case
   */
  private generateProjectKey(projectName: string): string {
    return projectName
      .toLowerCase()
      .replace(/\s+/g, '-')
      .replace(/[^a-z0-9-]/g, '');
  }

  /**
   * Format story key for YAML
   *
   * Converts story ID and title to kebab-case key
   * Example: Story with id "4-7" and title "Sprint Status File Generation"
   *         → "4-7-sprint-status-file-generation"
   *
   * @param story Story object
   * @returns Formatted story key
   */
  private formatStoryKey(story: Story): string {
    // Convert title to kebab-case
    const titleKebab = story.title
      .toLowerCase()
      .replace(/[&]/g, '') // Remove ampersands
      .replace(/\s+/g, '-') // Replace spaces with hyphens
      .replace(/[^a-z0-9-]/g, '') // Remove non-alphanumeric except hyphens
      .replace(/-+/g, '-') // Replace multiple hyphens with single
      .replace(/^-|-$/g, ''); // Trim leading/trailing hyphens

    return `${story.id}-${titleKebab}`;
  }
}
